### ISSUE TITLE
Sync variant of this lib?

### ISSUE THREAD

**Issue by 7iomka** [niksy/get-sass-vars#6]
Hi.
I want to use your lib inside `tailwind.config.js` to transform my sass variables and set this values in config.
For this `sync` api is required :(

Fore example issue
https://github.com/tailwindlabs/tailwindcss/discussions/1622

**Comment by niksy** [comment]
Sure, I could look into it. I see that you’ve made PR so I will see if there’s something I could use.

**Comment by 7iomka** [comment]
> Sure, I could look into it. I see that you’ve made PR so I will see if there’s something I could use.

I would be very grateful if you would also quickly release it to release changes from PR or similar changes (my changes don't break any currently functionality, but may be some code deduplication needed for better look, that is just draft for demonstration that async api is non-required option for your plugin if all dependencies has sync api.
So, if that module common usage case is to prepare some build-time configurations (like in my case), async api is a problem, but let it remain for users who are already using it.
I am waiting)

**Comment by niksy** [comment]
I think Tailwind is in the wrong here because they should provide Promise based configuration which majority of the ecosystem follows. It just happens that both Sass and PostCSS offer sync APIs but they should always be fallback.

I can’t guarantee anything on when it will be done, if you need it quickly, you can fork this repository and use your version and switch to this when it’s done.

**Comment by niksy** [comment]
Done in [3.4.0](https://github.com/niksy/get-sass-vars/releases/tag/v3.4.0).

**Comment by 7iomka** [comment]
> Done in [3.4.0](https://github.com/niksy/get-sass-vars/releases/tag/v3.4.0).

Thank you very much!
